# Generated by Django 3.1 on 2020-08-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='judul',
            field=models.CharField(default='hello', max_length=255),
            preserve_default=False,
        ),
    ]
