# Generated by Django 3.1 on 2020-08-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_article_judul'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='isi',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
