# Generated by Django 3.1 on 2020-08-17 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_datacsv_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dataCSV',
            new_name='datasCSV',
        ),
    ]
